/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { lazyRouteComponent } from '@tanstack/svelte-router'

import {
  Route as rootRouteImport,
  default as rootRouteComponent,
} from './routes/__root.svelte'
import {
  Route as IndexRouteImport,
  default as IndexRouteComponent,
} from './routes/index.svelte'
import {
  Route as StaticRouteImport,
  default as StaticRouteComponent,
} from './routes/static.svelte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: IndexRouteComponent,
})
const StaticRoute = StaticRouteImport.update({
  id: '/static',
  path: '/static',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: StaticRouteComponent,
})

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/static': typeof StaticRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/static': typeof StaticRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/static': typeof StaticRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/static'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/static'
  id: '__root__' | '/' | '/static'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StaticRoute: typeof StaticRoute
}

declare module '@tanstack/svelte-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/static': {
      id: '/static'
      path: '/static'
      fullPath: '/static'
      preLoaderRoute: typeof StaticRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StaticRoute: StaticRoute,
}
export const routeTree = rootRouteImport
  .update({
    component: rootRouteComponent,
  })
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/svelte-start'
declare module '@tanstack/svelte-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
