/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { lazyRouteComponent } from '@tanstack/svelte-router'

import {
  Route as rootRouteImport,
  default as rootRouteComponent,
} from './routes/__root.svelte'
import {
  Route as IndexRouteImport,
  default as IndexRouteComponent,
} from './routes/index.svelte'
import {
  Route as testsNormalPageRouteImport,
  default as testsNormalPageRouteComponent,
} from './routes/(tests)/normal-page.svelte'
import {
  Route as testsWithLoaderRouteImport,
  default as testsWithLoaderRouteComponent,
} from './routes/(tests)/with-loader.svelte'
import {
  Route as testsWithSearchRouteImport,
  default as testsWithSearchRouteComponent,
} from './routes/(tests)/with-search.svelte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: IndexRouteComponent,
})
const testsNormalPageRoute = testsNormalPageRouteImport
  .update({
    id: '/(tests)/normal-page',
    path: '/normal-page',
    getParentRoute: () => rootRouteImport,
  } as any)
  .update({
    component: testsNormalPageRouteComponent,
  })
const testsWithLoaderRoute = testsWithLoaderRouteImport
  .update({
    id: '/(tests)/with-loader',
    path: '/with-loader',
    getParentRoute: () => rootRouteImport,
  } as any)
  .update({
    component: testsWithLoaderRouteComponent,
  })
const testsWithSearchRoute = testsWithSearchRouteImport
  .update({
    id: '/(tests)/with-search',
    path: '/with-search',
    getParentRoute: () => rootRouteImport,
  } as any)
  .update({
    component: testsWithSearchRouteComponent,
  })

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/normal-page': typeof testsNormalPageRoute
  '/with-loader': typeof testsWithLoaderRoute
  '/with-search': typeof testsWithSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/normal-page': typeof testsNormalPageRoute
  '/with-loader': typeof testsWithLoaderRoute
  '/with-search': typeof testsWithSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(tests)/normal-page': typeof testsNormalPageRoute
  '/(tests)/with-loader': typeof testsWithLoaderRoute
  '/(tests)/with-search': typeof testsWithSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/normal-page' | '/with-loader' | '/with-search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/normal-page' | '/with-loader' | '/with-search'
  id:
    | '__root__'
    | '/'
    | '/(tests)/normal-page'
    | '/(tests)/with-loader'
    | '/(tests)/with-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  testsNormalPageRoute: typeof testsNormalPageRoute
  testsWithLoaderRoute: typeof testsWithLoaderRoute
  testsWithSearchRoute: typeof testsWithSearchRoute
}

declare module '@tanstack/svelte-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/normal-page': {
      id: '/(tests)/normal-page'
      path: '/normal-page'
      fullPath: '/normal-page'
      preLoaderRoute: typeof testsNormalPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/with-loader': {
      id: '/(tests)/with-loader'
      path: '/with-loader'
      fullPath: '/with-loader'
      preLoaderRoute: typeof testsWithLoaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/with-search': {
      id: '/(tests)/with-search'
      path: '/with-search'
      fullPath: '/with-search'
      preLoaderRoute: typeof testsWithSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  testsNormalPageRoute: testsNormalPageRoute,
  testsWithLoaderRoute: testsWithLoaderRoute,
  testsWithSearchRoute: testsWithSearchRoute,
}
export const routeTree = rootRouteImport
  .update({
    component: rootRouteComponent,
  })
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/svelte-start'
declare module '@tanstack/svelte-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
