/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { lazyRouteComponent } from '@tanstack/svelte-router'

import {
  Route as rootRouteImport,
  default as rootRouteComponent,
} from './routes/__root.svelte'
import {
  Route as LibraryRouteImport,
  default as LibraryRouteComponent,
} from './routes/_library.svelte'
import {
  Route as ProjectIndexRouteImport,
  default as ProjectIndexRouteComponent,
} from './routes/$project.index.svelte'
import {
  Route as LibraryIndexRouteImport,
  default as LibraryIndexRouteComponent,
} from './routes/_library.index.svelte'
import {
  Route as LibraryProjectRouteImport,
  default as LibraryProjectRouteComponent,
} from './routes/_library.$project.svelte'
import {
  Route as ProjectVersionDocsIndexRouteImport,
  default as ProjectVersionDocsIndexRouteComponent,
} from './routes/$project.$version.docs.index.svelte'
import {
  Route as LibraryProjectVersionIndexRouteImport,
  default as LibraryProjectVersionIndexRouteComponent,
} from './routes/_library.$project.$version.index.svelte'
import {
  Route as ProjectVersionDocsFrameworkFrameworkRouteImport,
  default as ProjectVersionDocsFrameworkFrameworkRouteComponent,
} from './routes/$project.$version.docs.framework.$framework.svelte'
import {
  Route as ProjectVersionDocsFrameworkFrameworkIndexRouteImport,
  default as ProjectVersionDocsFrameworkFrameworkIndexRouteComponent,
} from './routes/$project.$version.docs.framework.$framework.index.svelte'
import {
  Route as ProjectVersionDocsFrameworkFrameworkSplatRouteImport,
  default as ProjectVersionDocsFrameworkFrameworkSplatRouteComponent,
} from './routes/$project.$version.docs.framework.$framework.$.svelte'
import {
  Route as ProjectVersionDocsFrameworkFrameworkExamplesSplatRouteImport,
  default as ProjectVersionDocsFrameworkFrameworkExamplesSplatRouteComponent,
} from './routes/$project.$version.docs.framework.$framework.examples.$.svelte'

const LibraryRoute = LibraryRouteImport.update({
  id: '/_library',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: LibraryRouteComponent,
})
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/$project/',
  path: '/$project/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: ProjectIndexRouteComponent,
})
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any).update({
  component: LibraryIndexRouteComponent,
})
const LibraryProjectRoute = LibraryProjectRouteImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => LibraryRoute,
} as any).update({
  component: LibraryProjectRouteComponent,
})
const ProjectVersionDocsIndexRoute = ProjectVersionDocsIndexRouteImport.update({
  id: '/$project/$version/docs/',
  path: '/$project/$version/docs/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: ProjectVersionDocsIndexRouteComponent,
})
const LibraryProjectVersionIndexRoute =
  LibraryProjectVersionIndexRouteImport.update({
    id: '/$version/',
    path: '/$version/',
    getParentRoute: () => LibraryProjectRoute,
  } as any).update({
    component: LibraryProjectVersionIndexRouteComponent,
  })
const ProjectVersionDocsFrameworkFrameworkRoute =
  ProjectVersionDocsFrameworkFrameworkRouteImport.update({
    id: '/$project/$version/docs/framework/$framework',
    path: '/$project/$version/docs/framework/$framework',
    getParentRoute: () => rootRouteImport,
  } as any).update({
    component: ProjectVersionDocsFrameworkFrameworkRouteComponent,
  })
const ProjectVersionDocsFrameworkFrameworkIndexRoute =
  ProjectVersionDocsFrameworkFrameworkIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectVersionDocsFrameworkFrameworkRoute,
  } as any).update({
    component: ProjectVersionDocsFrameworkFrameworkIndexRouteComponent,
  })
const ProjectVersionDocsFrameworkFrameworkSplatRoute =
  ProjectVersionDocsFrameworkFrameworkSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => ProjectVersionDocsFrameworkFrameworkRoute,
  } as any).update({
    component: ProjectVersionDocsFrameworkFrameworkSplatRouteComponent,
  })
const ProjectVersionDocsFrameworkFrameworkExamplesSplatRoute =
  ProjectVersionDocsFrameworkFrameworkExamplesSplatRouteImport.update({
    id: '/examples/$',
    path: '/examples/$',
    getParentRoute: () => ProjectVersionDocsFrameworkFrameworkRoute,
  } as any).update({
    component: ProjectVersionDocsFrameworkFrameworkExamplesSplatRouteComponent,
  })

export interface FileRoutesByFullPath {
  '/': typeof LibraryIndexRoute
  '/$project': typeof LibraryProjectRouteWithChildren
  '/$project/': typeof ProjectIndexRoute
  '/$project/$version/docs/': typeof ProjectVersionDocsIndexRoute
  '/$project/$version/': typeof LibraryProjectVersionIndexRoute
  '/$project/$version/docs/framework/$framework': typeof ProjectVersionDocsFrameworkFrameworkRouteWithChildren
  '/$project/$version/docs/framework/$framework/$': typeof ProjectVersionDocsFrameworkFrameworkSplatRoute
  '/$project/$version/docs/framework/$framework/': typeof ProjectVersionDocsFrameworkFrameworkIndexRoute
  '/$project/$version/docs/framework/$framework/examples/$': typeof ProjectVersionDocsFrameworkFrameworkExamplesSplatRoute
}
export interface FileRoutesByTo {
  '/$project': typeof ProjectIndexRoute
  '/': typeof LibraryIndexRoute
  '/$project/$version/docs': typeof ProjectVersionDocsIndexRoute
  '/$project/$version': typeof LibraryProjectVersionIndexRoute
  '/$project/$version/docs/framework/$framework/$': typeof ProjectVersionDocsFrameworkFrameworkSplatRoute
  '/$project/$version/docs/framework/$framework': typeof ProjectVersionDocsFrameworkFrameworkIndexRoute
  '/$project/$version/docs/framework/$framework/examples/$': typeof ProjectVersionDocsFrameworkFrameworkExamplesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_library': typeof LibraryRouteWithChildren
  '/_library/$project': typeof LibraryProjectRouteWithChildren
  '/$project/': typeof ProjectIndexRoute
  '/_library/': typeof LibraryIndexRoute
  '/$project/$version/docs/': typeof ProjectVersionDocsIndexRoute
  '/_library/$project/$version/': typeof LibraryProjectVersionIndexRoute
  '/$project/$version/docs/framework/$framework': typeof ProjectVersionDocsFrameworkFrameworkRouteWithChildren
  '/$project/$version/docs/framework/$framework/$': typeof ProjectVersionDocsFrameworkFrameworkSplatRoute
  '/$project/$version/docs/framework/$framework/': typeof ProjectVersionDocsFrameworkFrameworkIndexRoute
  '/$project/$version/docs/framework/$framework/examples/$': typeof ProjectVersionDocsFrameworkFrameworkExamplesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$project'
    | '/$project/'
    | '/$project/$version/docs/'
    | '/$project/$version/'
    | '/$project/$version/docs/framework/$framework'
    | '/$project/$version/docs/framework/$framework/$'
    | '/$project/$version/docs/framework/$framework/'
    | '/$project/$version/docs/framework/$framework/examples/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$project'
    | '/'
    | '/$project/$version/docs'
    | '/$project/$version'
    | '/$project/$version/docs/framework/$framework/$'
    | '/$project/$version/docs/framework/$framework'
    | '/$project/$version/docs/framework/$framework/examples/$'
  id:
    | '__root__'
    | '/_library'
    | '/_library/$project'
    | '/$project/'
    | '/_library/'
    | '/$project/$version/docs/'
    | '/_library/$project/$version/'
    | '/$project/$version/docs/framework/$framework'
    | '/$project/$version/docs/framework/$framework/$'
    | '/$project/$version/docs/framework/$framework/'
    | '/$project/$version/docs/framework/$framework/examples/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LibraryRoute: typeof LibraryRouteWithChildren
  ProjectIndexRoute: typeof ProjectIndexRoute
  ProjectVersionDocsIndexRoute: typeof ProjectVersionDocsIndexRoute
  ProjectVersionDocsFrameworkFrameworkRoute: typeof ProjectVersionDocsFrameworkFrameworkRouteWithChildren
}

declare module '@tanstack/svelte-router' {
  interface FileRoutesByPath {
    '/_library': {
      id: '/_library'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$project/': {
      id: '/$project/'
      path: '/$project'
      fullPath: '/$project/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_library/': {
      id: '/_library/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/_library/$project': {
      id: '/_library/$project'
      path: '/$project'
      fullPath: '/$project'
      preLoaderRoute: typeof LibraryProjectRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/$project/$version/docs/': {
      id: '/$project/$version/docs/'
      path: '/$project/$version/docs'
      fullPath: '/$project/$version/docs/'
      preLoaderRoute: typeof ProjectVersionDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_library/$project/$version/': {
      id: '/_library/$project/$version/'
      path: '/$version'
      fullPath: '/$project/$version/'
      preLoaderRoute: typeof LibraryProjectVersionIndexRouteImport
      parentRoute: typeof LibraryProjectRoute
    }
    '/$project/$version/docs/framework/$framework': {
      id: '/$project/$version/docs/framework/$framework'
      path: '/$project/$version/docs/framework/$framework'
      fullPath: '/$project/$version/docs/framework/$framework'
      preLoaderRoute: typeof ProjectVersionDocsFrameworkFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$project/$version/docs/framework/$framework/': {
      id: '/$project/$version/docs/framework/$framework/'
      path: '/'
      fullPath: '/$project/$version/docs/framework/$framework/'
      preLoaderRoute: typeof ProjectVersionDocsFrameworkFrameworkIndexRouteImport
      parentRoute: typeof ProjectVersionDocsFrameworkFrameworkRoute
    }
    '/$project/$version/docs/framework/$framework/$': {
      id: '/$project/$version/docs/framework/$framework/$'
      path: '/$'
      fullPath: '/$project/$version/docs/framework/$framework/$'
      preLoaderRoute: typeof ProjectVersionDocsFrameworkFrameworkSplatRouteImport
      parentRoute: typeof ProjectVersionDocsFrameworkFrameworkRoute
    }
    '/$project/$version/docs/framework/$framework/examples/$': {
      id: '/$project/$version/docs/framework/$framework/examples/$'
      path: '/examples/$'
      fullPath: '/$project/$version/docs/framework/$framework/examples/$'
      preLoaderRoute: typeof ProjectVersionDocsFrameworkFrameworkExamplesSplatRouteImport
      parentRoute: typeof ProjectVersionDocsFrameworkFrameworkRoute
    }
  }
}

interface LibraryProjectRouteChildren {
  LibraryProjectVersionIndexRoute: typeof LibraryProjectVersionIndexRoute
}

const LibraryProjectRouteChildren: LibraryProjectRouteChildren = {
  LibraryProjectVersionIndexRoute: LibraryProjectVersionIndexRoute,
}

const LibraryProjectRouteWithChildren = LibraryProjectRoute._addFileChildren(
  LibraryProjectRouteChildren,
)

interface LibraryRouteChildren {
  LibraryProjectRoute: typeof LibraryProjectRouteWithChildren
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryProjectRoute: LibraryProjectRouteWithChildren,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

interface ProjectVersionDocsFrameworkFrameworkRouteChildren {
  ProjectVersionDocsFrameworkFrameworkSplatRoute: typeof ProjectVersionDocsFrameworkFrameworkSplatRoute
  ProjectVersionDocsFrameworkFrameworkIndexRoute: typeof ProjectVersionDocsFrameworkFrameworkIndexRoute
  ProjectVersionDocsFrameworkFrameworkExamplesSplatRoute: typeof ProjectVersionDocsFrameworkFrameworkExamplesSplatRoute
}

const ProjectVersionDocsFrameworkFrameworkRouteChildren: ProjectVersionDocsFrameworkFrameworkRouteChildren =
  {
    ProjectVersionDocsFrameworkFrameworkSplatRoute:
      ProjectVersionDocsFrameworkFrameworkSplatRoute,
    ProjectVersionDocsFrameworkFrameworkIndexRoute:
      ProjectVersionDocsFrameworkFrameworkIndexRoute,
    ProjectVersionDocsFrameworkFrameworkExamplesSplatRoute:
      ProjectVersionDocsFrameworkFrameworkExamplesSplatRoute,
  }

const ProjectVersionDocsFrameworkFrameworkRouteWithChildren =
  ProjectVersionDocsFrameworkFrameworkRoute._addFileChildren(
    ProjectVersionDocsFrameworkFrameworkRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  LibraryRoute: LibraryRouteWithChildren,
  ProjectIndexRoute: ProjectIndexRoute,
  ProjectVersionDocsIndexRoute: ProjectVersionDocsIndexRoute,
  ProjectVersionDocsFrameworkFrameworkRoute:
    ProjectVersionDocsFrameworkFrameworkRouteWithChildren,
}
export const routeTree = rootRouteImport
  .update({
    component: rootRouteComponent,
  })
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/svelte-start'
declare module '@tanstack/svelte-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
