/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { lazyRouteComponent } from '@tanstack/svelte-router'

import {
  Route as rootRouteImport,
  default as rootRouteComponent,
} from './routes/__root.svelte'
import {
  Route as IndexRouteImport,
  default as IndexRouteComponent,
} from './routes/index.svelte'
import {
  Route as LayoutRouteImport,
  default as LayoutRouteComponent,
} from './routes/_layout.svelte'
import { Route as EditingARouteImport } from './routes/editing-a'
import { Route as EditingBRouteImport } from './routes/editing-b'
import { Route as NotRemountDepsRouteImport } from './routes/notRemountDeps'
import {
  Route as PostsRouteImport,
  default as PostsRouteComponent,
} from './routes/posts.svelte'
import { Route as RemountDepsRouteImport } from './routes/remountDeps'
import { Route as SfcComponentRouteImport } from './routes/sfcComponent'
import {
  Route as Char45824Char54620Char48124Char44397RouteImport,
  default as Char45824Char54620Char48124Char44397RouteComponent,
} from './routes/대한민국.svelte'
import {
  Route as anotherGroupOnlyrouteinsideRouteImport,
  default as anotherGroupOnlyrouteinsideRouteComponent,
} from './routes/(another-group)/onlyrouteinside.svelte'
import {
  Route as groupLayoutRouteImport,
  default as groupLayoutRouteComponent,
} from './routes/(group)/_layout.svelte'
import {
  Route as groupInsideRouteImport,
  default as groupInsideRouteComponent,
} from './routes/(group)/inside.svelte'
import {
  Route as groupLazyinsideRouteImport,
  default as groupLazyinsideRouteComponent,
} from './routes/(group)/lazyinside.svelte'
import {
  Route as LayoutLayout2RouteImport,
  default as LayoutLayout2RouteComponent,
} from './routes/_layout/_layout-2.svelte'
import {
  Route as PostsIndexRouteImport,
  default as PostsIndexRouteComponent,
} from './routes/posts.index.svelte'
import {
  Route as PostsPostIdRouteImport,
  default as PostsPostIdRouteComponent,
} from './routes/posts.$postId.svelte'
import {
  Route as groupLayoutInsidelayoutRouteImport,
  default as groupLayoutInsidelayoutRouteComponent,
} from './routes/(group)/_layout.insidelayout.svelte'
import {
  Route as groupSubfolderInsideRouteImport,
  default as groupSubfolderInsideRouteComponent,
} from './routes/(group)/subfolder/inside.svelte'
import {
  Route as LayoutLayout2LayoutARouteImport,
  default as LayoutLayout2LayoutARouteComponent,
} from './routes/_layout/_layout-2/layout-a.svelte'
import {
  Route as LayoutLayout2LayoutBRouteImport,
  default as LayoutLayout2LayoutBRouteComponent,
} from './routes/_layout/_layout-2/layout-b.svelte'
import {
  Route as PostsPostIdEditRouteImport,
  default as PostsPostIdEditRouteComponent,
} from './routes/posts_.$postId.edit.svelte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: IndexRouteComponent,
})
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: LayoutRouteComponent,
})
const EditingARoute = EditingARouteImport.update({
  id: '/editing-a',
  path: '/editing-a',
  getParentRoute: () => rootRouteImport,
} as any)
const EditingBRoute = EditingBRouteImport.update({
  id: '/editing-b',
  path: '/editing-b',
  getParentRoute: () => rootRouteImport,
} as any)
const NotRemountDepsRoute = NotRemountDepsRouteImport.update({
  id: '/notRemountDeps',
  path: '/notRemountDeps',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: PostsRouteComponent,
})
const RemountDepsRoute = RemountDepsRouteImport.update({
  id: '/remountDeps',
  path: '/remountDeps',
  getParentRoute: () => rootRouteImport,
} as any)
const SfcComponentRoute = SfcComponentRouteImport.update({
  id: '/sfcComponent',
  path: '/sfcComponent',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/sfcComponent.component.svelte'),
    'default',
  ),
})
const Char45824Char54620Char48124Char44397Route =
  Char45824Char54620Char48124Char44397RouteImport.update({
    id: '/대한민국',
    path: '/대한민국',
    getParentRoute: () => rootRouteImport,
  } as any).update({
    component: Char45824Char54620Char48124Char44397RouteComponent,
  })
const anotherGroupOnlyrouteinsideRoute = anotherGroupOnlyrouteinsideRouteImport
  .update({
    id: '/(another-group)/onlyrouteinside',
    path: '/onlyrouteinside',
    getParentRoute: () => rootRouteImport,
  } as any)
  .update({
    component: anotherGroupOnlyrouteinsideRouteComponent,
  })
const groupLayoutRoute = groupLayoutRouteImport
  .update({
    id: '/(group)/_layout',
    getParentRoute: () => rootRouteImport,
  } as any)
  .update({
    component: groupLayoutRouteComponent,
  })
const groupInsideRoute = groupInsideRouteImport
  .update({
    id: '/(group)/inside',
    path: '/inside',
    getParentRoute: () => rootRouteImport,
  } as any)
  .update({
    component: groupInsideRouteComponent,
  })
const groupLazyinsideRoute = groupLazyinsideRouteImport
  .update({
    id: '/(group)/lazyinside',
    path: '/lazyinside',
    getParentRoute: () => rootRouteImport,
  } as any)
  .update({
    component: groupLazyinsideRouteComponent,
  })
const LayoutLayout2Route = LayoutLayout2RouteImport.update({
  id: '/_layout-2',
  getParentRoute: () => LayoutRoute,
} as any).update({
  component: LayoutLayout2RouteComponent,
})
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any).update({
  component: PostsIndexRouteComponent,
})
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any).update({
  component: PostsPostIdRouteComponent,
})
const groupLayoutInsidelayoutRoute = groupLayoutInsidelayoutRouteImport
  .update({
    id: '/insidelayout',
    path: '/insidelayout',
    getParentRoute: () => groupLayoutRoute,
  } as any)
  .update({
    component: groupLayoutInsidelayoutRouteComponent,
  })
const groupSubfolderInsideRoute = groupSubfolderInsideRouteImport
  .update({
    id: '/(group)/subfolder/inside',
    path: '/subfolder/inside',
    getParentRoute: () => rootRouteImport,
  } as any)
  .update({
    component: groupSubfolderInsideRouteComponent,
  })
const LayoutLayout2LayoutARoute = LayoutLayout2LayoutARouteImport.update({
  id: '/layout-a',
  path: '/layout-a',
  getParentRoute: () => LayoutLayout2Route,
} as any).update({
  component: LayoutLayout2LayoutARouteComponent,
})
const LayoutLayout2LayoutBRoute = LayoutLayout2LayoutBRouteImport.update({
  id: '/layout-b',
  path: '/layout-b',
  getParentRoute: () => LayoutLayout2Route,
} as any).update({
  component: LayoutLayout2LayoutBRouteComponent,
})
const PostsPostIdEditRoute = PostsPostIdEditRouteImport.update({
  id: '/posts_/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: PostsPostIdEditRouteComponent,
})

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editing-a': typeof EditingARoute
  '/editing-b': typeof EditingBRoute
  '/notRemountDeps': typeof NotRemountDepsRoute
  '/posts': typeof PostsRouteWithChildren
  '/remountDeps': typeof RemountDepsRoute
  '/sfcComponent': typeof SfcComponentRoute
  '/대한민국': typeof Char45824Char54620Char48124Char44397Route
  '/onlyrouteinside': typeof anotherGroupOnlyrouteinsideRoute
  '/inside': typeof groupInsideRoute
  '/lazyinside': typeof groupLazyinsideRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/': typeof PostsIndexRoute
  '/insidelayout': typeof groupLayoutInsidelayoutRoute
  '/subfolder/inside': typeof groupSubfolderInsideRoute
  '/layout-a': typeof LayoutLayout2LayoutARoute
  '/layout-b': typeof LayoutLayout2LayoutBRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editing-a': typeof EditingARoute
  '/editing-b': typeof EditingBRoute
  '/notRemountDeps': typeof NotRemountDepsRoute
  '/remountDeps': typeof RemountDepsRoute
  '/sfcComponent': typeof SfcComponentRoute
  '/대한민국': typeof Char45824Char54620Char48124Char44397Route
  '/onlyrouteinside': typeof anotherGroupOnlyrouteinsideRoute
  '/inside': typeof groupInsideRoute
  '/lazyinside': typeof groupLazyinsideRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts': typeof PostsIndexRoute
  '/insidelayout': typeof groupLayoutInsidelayoutRoute
  '/subfolder/inside': typeof groupSubfolderInsideRoute
  '/layout-a': typeof LayoutLayout2LayoutARoute
  '/layout-b': typeof LayoutLayout2LayoutBRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/editing-a': typeof EditingARoute
  '/editing-b': typeof EditingBRoute
  '/notRemountDeps': typeof NotRemountDepsRoute
  '/posts': typeof PostsRouteWithChildren
  '/remountDeps': typeof RemountDepsRoute
  '/sfcComponent': typeof SfcComponentRoute
  '/대한민국': typeof Char45824Char54620Char48124Char44397Route
  '/(another-group)/onlyrouteinside': typeof anotherGroupOnlyrouteinsideRoute
  '/(group)/_layout': typeof groupLayoutRouteWithChildren
  '/(group)/inside': typeof groupInsideRoute
  '/(group)/lazyinside': typeof groupLazyinsideRoute
  '/_layout/_layout-2': typeof LayoutLayout2RouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/': typeof PostsIndexRoute
  '/(group)/_layout/insidelayout': typeof groupLayoutInsidelayoutRoute
  '/(group)/subfolder/inside': typeof groupSubfolderInsideRoute
  '/_layout/_layout-2/layout-a': typeof LayoutLayout2LayoutARoute
  '/_layout/_layout-2/layout-b': typeof LayoutLayout2LayoutBRoute
  '/posts_/$postId/edit': typeof PostsPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editing-a'
    | '/editing-b'
    | '/notRemountDeps'
    | '/posts'
    | '/remountDeps'
    | '/sfcComponent'
    | '/대한민국'
    | '/onlyrouteinside'
    | '/inside'
    | '/lazyinside'
    | '/posts/$postId'
    | '/posts/'
    | '/insidelayout'
    | '/subfolder/inside'
    | '/layout-a'
    | '/layout-b'
    | '/posts/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editing-a'
    | '/editing-b'
    | '/notRemountDeps'
    | '/remountDeps'
    | '/sfcComponent'
    | '/대한민국'
    | '/onlyrouteinside'
    | '/inside'
    | '/lazyinside'
    | '/posts/$postId'
    | '/posts'
    | '/insidelayout'
    | '/subfolder/inside'
    | '/layout-a'
    | '/layout-b'
    | '/posts/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/editing-a'
    | '/editing-b'
    | '/notRemountDeps'
    | '/posts'
    | '/remountDeps'
    | '/sfcComponent'
    | '/대한민국'
    | '/(another-group)/onlyrouteinside'
    | '/(group)/_layout'
    | '/(group)/inside'
    | '/(group)/lazyinside'
    | '/_layout/_layout-2'
    | '/posts/$postId'
    | '/posts/'
    | '/(group)/_layout/insidelayout'
    | '/(group)/subfolder/inside'
    | '/_layout/_layout-2/layout-a'
    | '/_layout/_layout-2/layout-b'
    | '/posts_/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  EditingARoute: typeof EditingARoute
  EditingBRoute: typeof EditingBRoute
  NotRemountDepsRoute: typeof NotRemountDepsRoute
  PostsRoute: typeof PostsRouteWithChildren
  RemountDepsRoute: typeof RemountDepsRoute
  SfcComponentRoute: typeof SfcComponentRoute
  Char45824Char54620Char48124Char44397Route: typeof Char45824Char54620Char48124Char44397Route
  anotherGroupOnlyrouteinsideRoute: typeof anotherGroupOnlyrouteinsideRoute
  groupLayoutRoute: typeof groupLayoutRouteWithChildren
  groupInsideRoute: typeof groupInsideRoute
  groupLazyinsideRoute: typeof groupLazyinsideRoute
  groupSubfolderInsideRoute: typeof groupSubfolderInsideRoute
  PostsPostIdEditRoute: typeof PostsPostIdEditRoute
}

declare module '@tanstack/svelte-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editing-a': {
      id: '/editing-a'
      path: '/editing-a'
      fullPath: '/editing-a'
      preLoaderRoute: typeof EditingARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editing-b': {
      id: '/editing-b'
      path: '/editing-b'
      fullPath: '/editing-b'
      preLoaderRoute: typeof EditingBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notRemountDeps': {
      id: '/notRemountDeps'
      path: '/notRemountDeps'
      fullPath: '/notRemountDeps'
      preLoaderRoute: typeof NotRemountDepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remountDeps': {
      id: '/remountDeps'
      path: '/remountDeps'
      fullPath: '/remountDeps'
      preLoaderRoute: typeof RemountDepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sfcComponent': {
      id: '/sfcComponent'
      path: '/sfcComponent'
      fullPath: '/sfcComponent'
      preLoaderRoute: typeof SfcComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/대한민국': {
      id: '/대한민국'
      path: '/대한민국'
      fullPath: '/대한민국'
      preLoaderRoute: typeof Char45824Char54620Char48124Char44397RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(another-group)/onlyrouteinside': {
      id: '/(another-group)/onlyrouteinside'
      path: '/onlyrouteinside'
      fullPath: '/onlyrouteinside'
      preLoaderRoute: typeof anotherGroupOnlyrouteinsideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(group)/_layout': {
      id: '/(group)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof groupLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(group)/inside': {
      id: '/(group)/inside'
      path: '/inside'
      fullPath: '/inside'
      preLoaderRoute: typeof groupInsideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(group)/lazyinside': {
      id: '/(group)/lazyinside'
      path: '/lazyinside'
      fullPath: '/lazyinside'
      preLoaderRoute: typeof groupLazyinsideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_layout-2': {
      id: '/_layout/_layout-2'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutLayout2RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/(group)/_layout/insidelayout': {
      id: '/(group)/_layout/insidelayout'
      path: '/insidelayout'
      fullPath: '/insidelayout'
      preLoaderRoute: typeof groupLayoutInsidelayoutRouteImport
      parentRoute: typeof groupLayoutRoute
    }
    '/(group)/subfolder/inside': {
      id: '/(group)/subfolder/inside'
      path: '/subfolder/inside'
      fullPath: '/subfolder/inside'
      preLoaderRoute: typeof groupSubfolderInsideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_layout-2/layout-a': {
      id: '/_layout/_layout-2/layout-a'
      path: '/layout-a'
      fullPath: '/layout-a'
      preLoaderRoute: typeof LayoutLayout2LayoutARouteImport
      parentRoute: typeof LayoutLayout2Route
    }
    '/_layout/_layout-2/layout-b': {
      id: '/_layout/_layout-2/layout-b'
      path: '/layout-b'
      fullPath: '/layout-b'
      preLoaderRoute: typeof LayoutLayout2LayoutBRouteImport
      parentRoute: typeof LayoutLayout2Route
    }
    '/posts_/$postId/edit': {
      id: '/posts_/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof PostsPostIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutLayout2RouteChildren {
  LayoutLayout2LayoutARoute: typeof LayoutLayout2LayoutARoute
  LayoutLayout2LayoutBRoute: typeof LayoutLayout2LayoutBRoute
}

const LayoutLayout2RouteChildren: LayoutLayout2RouteChildren = {
  LayoutLayout2LayoutARoute: LayoutLayout2LayoutARoute,
  LayoutLayout2LayoutBRoute: LayoutLayout2LayoutBRoute,
}

const LayoutLayout2RouteWithChildren = LayoutLayout2Route._addFileChildren(
  LayoutLayout2RouteChildren,
)

interface LayoutRouteChildren {
  LayoutLayout2Route: typeof LayoutLayout2RouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutLayout2Route: LayoutLayout2RouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface groupLayoutRouteChildren {
  groupLayoutInsidelayoutRoute: typeof groupLayoutInsidelayoutRoute
}

const groupLayoutRouteChildren: groupLayoutRouteChildren = {
  groupLayoutInsidelayoutRoute: groupLayoutInsidelayoutRoute,
}

const groupLayoutRouteWithChildren = groupLayoutRoute._addFileChildren(
  groupLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  EditingARoute: EditingARoute,
  EditingBRoute: EditingBRoute,
  NotRemountDepsRoute: NotRemountDepsRoute,
  PostsRoute: PostsRouteWithChildren,
  RemountDepsRoute: RemountDepsRoute,
  SfcComponentRoute: SfcComponentRoute,
  Char45824Char54620Char48124Char44397Route:
    Char45824Char54620Char48124Char44397Route,
  anotherGroupOnlyrouteinsideRoute: anotherGroupOnlyrouteinsideRoute,
  groupLayoutRoute: groupLayoutRouteWithChildren,
  groupInsideRoute: groupInsideRoute,
  groupLazyinsideRoute: groupLazyinsideRoute,
  groupSubfolderInsideRoute: groupSubfolderInsideRoute,
  PostsPostIdEditRoute: PostsPostIdEditRoute,
}
export const routeTree = rootRouteImport
  .update({
    component: rootRouteComponent,
  })
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
