/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { lazyRouteComponent } from '@tanstack/svelte-router'

import {
  Route as rootRouteImport,
  default as rootRouteComponent,
} from './routes/root.svelte'
import {
  Route as homeRouteImport,
  default as homeRouteComponent,
} from './routes/home.svelte'
import {
  Route as layoutFirstLayoutRouteImport,
  default as layoutFirstLayoutRouteComponent,
} from './routes/layout/first-layout.svelte'
import {
  Route as postsPostsRouteImport,
  default as postsPostsRouteComponent,
} from './routes/posts/posts.svelte'
import {
  Route as pipeRouteImport,
  default as pipeRouteComponent,
} from './routes/pipe.svelte'
import {
  Route as layoutSecondLayoutRouteImport,
  default as layoutSecondLayoutRouteComponent,
} from './routes/layout/second-layout.svelte'
import {
  Route as ClassicHelloRouteRouteImport,
  default as ClassicHelloRouteRouteComponent,
} from './routes/file-based-subtree/hello/route.svelte'
import {
  Route as postsPostsHomeRouteImport,
  default as postsPostsHomeRouteComponent,
} from './routes/posts/posts-home.svelte'
import {
  Route as postsPostsDetailRouteImport,
  default as postsPostsDetailRouteComponent,
} from './routes/posts/posts-detail.svelte'
import {
  Route as ClassicHelloIndexRouteImport,
  default as ClassicHelloIndexRouteComponent,
} from './routes/file-based-subtree/hello/index.svelte'
import {
  Route as ClassicHelloUniverseRouteImport,
  default as ClassicHelloUniverseRouteComponent,
} from './routes/file-based-subtree/hello/universe.svelte'
import {
  Route as ClassicHelloWorldRouteImport,
  default as ClassicHelloWorldRouteComponent,
} from './routes/file-based-subtree/hello/world.svelte'
import {
  Route as aRouteImport,
  default as aRouteComponent,
} from './routes/a.svelte'
import {
  Route as bRouteImport,
  default as bRouteComponent,
} from './routes/b.svelte'

const homeRoute = homeRouteImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)
  .update({
    component: homeRouteComponent,
  })
const layoutFirstLayoutRoute = layoutFirstLayoutRouteImport
  .update({
    id: '/_first',
    getParentRoute: () => rootRouteImport,
  } as any)
  .update({
    component: layoutFirstLayoutRouteComponent,
  })
const postsPostsRoute = postsPostsRouteImport
  .update({
    id: '/posts',
    path: '/posts',
    getParentRoute: () => rootRouteImport,
  } as any)
  .update({
    component: postsPostsRouteComponent,
  })
const pipeRoute = pipeRouteImport
  .update({
    id: '/special|pipe',
    path: '/special|pipe',
    getParentRoute: () => rootRouteImport,
  } as any)
  .update({
    component: pipeRouteComponent,
  })
const layoutSecondLayoutRoute = layoutSecondLayoutRouteImport
  .update({
    id: '/_second-layout',
    getParentRoute: () => layoutFirstLayoutRoute,
  } as any)
  .update({
    component: layoutSecondLayoutRouteComponent,
  })
const ClassicHelloRouteRoute = ClassicHelloRouteRouteImport.update({
  id: '/classic/hello',
  path: '/classic/hello',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: ClassicHelloRouteRouteComponent,
})
const postsPostsHomeRoute = postsPostsHomeRouteImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => postsPostsRoute,
  } as any)
  .update({
    component: postsPostsHomeRouteComponent,
  })
const postsPostsDetailRoute = postsPostsDetailRouteImport
  .update({
    id: '/$postId',
    path: '/$postId',
    getParentRoute: () => postsPostsRoute,
  } as any)
  .update({
    component: postsPostsDetailRouteComponent,
  })
const ClassicHelloIndexRoute = ClassicHelloIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClassicHelloRouteRoute,
} as any).update({
  component: ClassicHelloIndexRouteComponent,
})
const ClassicHelloUniverseRoute = ClassicHelloUniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => ClassicHelloRouteRoute,
} as any).update({
  component: ClassicHelloUniverseRouteComponent,
})
const ClassicHelloWorldRoute = ClassicHelloWorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => ClassicHelloRouteRoute,
} as any).update({
  component: ClassicHelloWorldRouteComponent,
})
const aRoute = aRouteImport
  .update({
    id: '/route-without-file/layout-a',
    path: '/route-without-file/layout-a',
    getParentRoute: () => layoutSecondLayoutRoute,
  } as any)
  .update({
    component: aRouteComponent,
  })
const bRoute = bRouteImport
  .update({
    id: '/route-without-file/layout-b',
    path: '/route-without-file/layout-b',
    getParentRoute: () => layoutSecondLayoutRoute,
  } as any)
  .update({
    component: bRouteComponent,
  })

export interface FileRoutesByFullPath {
  '/': typeof homeRoute
  '/posts': typeof postsPostsRouteWithChildren
  '/special|pipe': typeof pipeRoute
  '/classic/hello': typeof ClassicHelloRouteRouteWithChildren
  '/posts/': typeof postsPostsHomeRoute
  '/posts/$postId': typeof postsPostsDetailRoute
  '/classic/hello/universe': typeof ClassicHelloUniverseRoute
  '/classic/hello/world': typeof ClassicHelloWorldRoute
  '/classic/hello/': typeof ClassicHelloIndexRoute
  '/route-without-file/layout-a': typeof aRoute
  '/route-without-file/layout-b': typeof bRoute
}
export interface FileRoutesByTo {
  '/': typeof homeRoute
  '/special|pipe': typeof pipeRoute
  '/posts': typeof postsPostsHomeRoute
  '/posts/$postId': typeof postsPostsDetailRoute
  '/classic/hello/universe': typeof ClassicHelloUniverseRoute
  '/classic/hello/world': typeof ClassicHelloWorldRoute
  '/classic/hello': typeof ClassicHelloIndexRoute
  '/route-without-file/layout-a': typeof aRoute
  '/route-without-file/layout-b': typeof bRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof homeRoute
  '/_first': typeof layoutFirstLayoutRouteWithChildren
  '/posts': typeof postsPostsRouteWithChildren
  '/special|pipe': typeof pipeRoute
  '/classic/hello': typeof ClassicHelloRouteRouteWithChildren
  '/posts/': typeof postsPostsHomeRoute
  '/_first/_second-layout': typeof layoutSecondLayoutRouteWithChildren
  '/posts/$postId': typeof postsPostsDetailRoute
  '/classic/hello/universe': typeof ClassicHelloUniverseRoute
  '/classic/hello/world': typeof ClassicHelloWorldRoute
  '/classic/hello/': typeof ClassicHelloIndexRoute
  '/_first/_second-layout/route-without-file/layout-a': typeof aRoute
  '/_first/_second-layout/route-without-file/layout-b': typeof bRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts'
    | '/special|pipe'
    | '/classic/hello'
    | '/posts/'
    | '/posts/$postId'
    | '/classic/hello/universe'
    | '/classic/hello/world'
    | '/classic/hello/'
    | '/route-without-file/layout-a'
    | '/route-without-file/layout-b'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/special|pipe'
    | '/posts'
    | '/posts/$postId'
    | '/classic/hello/universe'
    | '/classic/hello/world'
    | '/classic/hello'
    | '/route-without-file/layout-a'
    | '/route-without-file/layout-b'
  id:
    | '__root__'
    | '/'
    | '/_first'
    | '/posts'
    | '/special|pipe'
    | '/classic/hello'
    | '/posts/'
    | '/_first/_second-layout'
    | '/posts/$postId'
    | '/classic/hello/universe'
    | '/classic/hello/world'
    | '/classic/hello/'
    | '/_first/_second-layout/route-without-file/layout-a'
    | '/_first/_second-layout/route-without-file/layout-b'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeRoute: typeof homeRoute
  layoutFirstLayoutRoute: typeof layoutFirstLayoutRouteWithChildren
  postsPostsRoute: typeof postsPostsRouteWithChildren
  pipeRoute: typeof pipeRoute
  ClassicHelloRouteRoute: typeof ClassicHelloRouteRouteWithChildren
}

declare module '@tanstack/svelte-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_first': {
      id: '/_first'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof layoutFirstLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof postsPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special|pipe': {
      id: '/special|pipe'
      path: '/special|pipe'
      fullPath: '/special|pipe'
      preLoaderRoute: typeof pipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_first/_second-layout': {
      id: '/_first/_second-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof layoutSecondLayoutRouteImport
      parentRoute: typeof layoutFirstLayoutRoute
    }
    '/classic/hello': {
      id: '/classic/hello'
      path: '/classic/hello'
      fullPath: '/classic/hello'
      preLoaderRoute: typeof ClassicHelloRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof postsPostsHomeRouteImport
      parentRoute: typeof postsPostsRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof postsPostsDetailRouteImport
      parentRoute: typeof postsPostsRoute
    }
    '/classic/hello/': {
      id: '/classic/hello/'
      path: '/'
      fullPath: '/classic/hello/'
      preLoaderRoute: typeof ClassicHelloIndexRouteImport
      parentRoute: typeof ClassicHelloRouteRoute
    }
    '/classic/hello/universe': {
      id: '/classic/hello/universe'
      path: '/universe'
      fullPath: '/classic/hello/universe'
      preLoaderRoute: typeof ClassicHelloUniverseRouteImport
      parentRoute: typeof ClassicHelloRouteRoute
    }
    '/classic/hello/world': {
      id: '/classic/hello/world'
      path: '/world'
      fullPath: '/classic/hello/world'
      preLoaderRoute: typeof ClassicHelloWorldRouteImport
      parentRoute: typeof ClassicHelloRouteRoute
    }
    '/_first/_second-layout/route-without-file/layout-a': {
      id: '/_first/_second-layout/route-without-file/layout-a'
      path: '/route-without-file/layout-a'
      fullPath: '/route-without-file/layout-a'
      preLoaderRoute: typeof aRouteImport
      parentRoute: typeof layoutSecondLayoutRoute
    }
    '/_first/_second-layout/route-without-file/layout-b': {
      id: '/_first/_second-layout/route-without-file/layout-b'
      path: '/route-without-file/layout-b'
      fullPath: '/route-without-file/layout-b'
      preLoaderRoute: typeof bRouteImport
      parentRoute: typeof layoutSecondLayoutRoute
    }
  }
}

interface layoutSecondLayoutRouteChildren {
  aRoute: typeof aRoute
  bRoute: typeof bRoute
}

const layoutSecondLayoutRouteChildren: layoutSecondLayoutRouteChildren = {
  aRoute: aRoute,
  bRoute: bRoute,
}

const layoutSecondLayoutRouteWithChildren =
  layoutSecondLayoutRoute._addFileChildren(layoutSecondLayoutRouteChildren)

interface layoutFirstLayoutRouteChildren {
  layoutSecondLayoutRoute: typeof layoutSecondLayoutRouteWithChildren
}

const layoutFirstLayoutRouteChildren: layoutFirstLayoutRouteChildren = {
  layoutSecondLayoutRoute: layoutSecondLayoutRouteWithChildren,
}

const layoutFirstLayoutRouteWithChildren =
  layoutFirstLayoutRoute._addFileChildren(layoutFirstLayoutRouteChildren)

interface postsPostsRouteChildren {
  postsPostsHomeRoute: typeof postsPostsHomeRoute
  postsPostsDetailRoute: typeof postsPostsDetailRoute
}

const postsPostsRouteChildren: postsPostsRouteChildren = {
  postsPostsHomeRoute: postsPostsHomeRoute,
  postsPostsDetailRoute: postsPostsDetailRoute,
}

const postsPostsRouteWithChildren = postsPostsRoute._addFileChildren(
  postsPostsRouteChildren,
)

interface ClassicHelloRouteRouteChildren {
  ClassicHelloUniverseRoute: typeof ClassicHelloUniverseRoute
  ClassicHelloWorldRoute: typeof ClassicHelloWorldRoute
  ClassicHelloIndexRoute: typeof ClassicHelloIndexRoute
}

const ClassicHelloRouteRouteChildren: ClassicHelloRouteRouteChildren = {
  ClassicHelloUniverseRoute: ClassicHelloUniverseRoute,
  ClassicHelloWorldRoute: ClassicHelloWorldRoute,
  ClassicHelloIndexRoute: ClassicHelloIndexRoute,
}

const ClassicHelloRouteRouteWithChildren =
  ClassicHelloRouteRoute._addFileChildren(ClassicHelloRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  homeRoute: homeRoute,
  layoutFirstLayoutRoute: layoutFirstLayoutRouteWithChildren,
  postsPostsRoute: postsPostsRouteWithChildren,
  pipeRoute: pipeRoute,
  ClassicHelloRouteRoute: ClassicHelloRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  .update({
    component: rootRouteComponent,
  })
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/svelte-start'
declare module '@tanstack/svelte-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
