/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {
  createFileRoute,
  createLazyFileRoute,
  createRootRoute,
  lazyRouteComponent,
} from '@tanstack/svelte-router'

import { Route as ColocatedRouteImport } from './routes/colocated'
import { Route as SplitRouteImport } from './routes/split'

const rootRouteImport = createRootRoute()
const LazyonlyLazyRouteImport = createFileRoute('/lazyonly')()

const ColocatedRoute = ColocatedRouteImport.update({
  id: '/colocated',
  path: '/colocated',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/colocated.lazy.svelte').then((d) =>
    createLazyFileRoute('/colocated')({
      ...d.Route?.options,
      component: d.Route?.options.component ?? d.default,
    }),
  ),
)
const LazyonlyLazyRoute = LazyonlyLazyRouteImport.update({
  id: '/lazyonly',
  path: '/lazyonly',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/lazyonly.lazy.svelte').then((d) =>
    createLazyFileRoute('/lazyonly')({
      ...d.Route?.options,
      component: d.Route?.options.component ?? d.default,
    }),
  ),
)
const SplitRoute = SplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/split.lazy.svelte').then((d) =>
    createLazyFileRoute('/split')({
      ...d.Route?.options,
      component: d.Route?.options.component ?? d.default,
    }),
  ),
)

export interface FileRoutesByFullPath {
  '/colocated': typeof ColocatedRoute
  '/split': typeof SplitRoute
  '/lazyonly': typeof LazyonlyLazyRoute
}
export interface FileRoutesByTo {
  '/colocated': typeof ColocatedRoute
  '/split': typeof SplitRoute
  '/lazyonly': typeof LazyonlyLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/colocated': typeof ColocatedRoute
  '/split': typeof SplitRoute
  '/lazyonly': typeof LazyonlyLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/colocated' | '/split' | '/lazyonly'
  fileRoutesByTo: FileRoutesByTo
  to: '/colocated' | '/split' | '/lazyonly'
  id: '__root__' | '/colocated' | '/split' | '/lazyonly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ColocatedRoute: typeof ColocatedRoute
  SplitRoute: typeof SplitRoute
  LazyonlyLazyRoute: typeof LazyonlyLazyRoute
}

declare module '@tanstack/svelte-router' {
  interface FileRoutesByPath {
    '/colocated': {
      id: '/colocated'
      path: '/colocated'
      fullPath: '/colocated'
      preLoaderRoute: typeof ColocatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lazyonly': {
      id: '/lazyonly'
      path: '/lazyonly'
      fullPath: '/lazyonly'
      preLoaderRoute: typeof LazyonlyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split': {
      id: '/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ColocatedRoute: ColocatedRoute,
  SplitRoute: SplitRoute,
  LazyonlyLazyRoute: LazyonlyLazyRoute,
}
export const routeTree = rootRouteImport
  .update({
    component: lazyRouteComponent(
      () => import('./routes/__root.svelte'),
      'default',
    ),
  })
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
