/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { lazyRouteComponent } from '@tanstack/svelte-router'

import {
  Route as rootRouteImport,
  default as rootRouteComponent,
} from './routes/__root.svelte'
import {
  Route as IndexRouteImport,
  default as IndexRouteComponent,
} from './routes/index.svelte'
import {
  Route as AbortSignalRouteImport,
  default as AbortSignalRouteComponent,
} from './routes/abort-signal.svelte'
import {
  Route as ConsistentRouteImport,
  default as ConsistentRouteComponent,
} from './routes/consistent.svelte'
import {
  Route as DeadCodePreserveRouteImport,
  default as DeadCodePreserveRouteComponent,
} from './routes/dead-code-preserve.svelte'
import {
  Route as EnvOnlyRouteImport,
  default as EnvOnlyRouteComponent,
} from './routes/env-only.svelte'
import {
  Route as HeadersRouteImport,
  default as HeadersRouteComponent,
} from './routes/headers.svelte'
import {
  Route as IsomorphicFnsRouteImport,
  default as IsomorphicFnsRouteComponent,
} from './routes/isomorphic-fns.svelte'
import {
  Route as MultipartRouteImport,
  default as MultipartRouteComponent,
} from './routes/multipart.svelte'
import {
  Route as RawResponseRouteImport,
  default as RawResponseRouteComponent,
} from './routes/raw-response.svelte'
import {
  Route as ReturnNullRouteImport,
  default as ReturnNullRouteComponent,
} from './routes/return-null.svelte'
import {
  Route as SerializeFormDataRouteImport,
  default as SerializeFormDataRouteComponent,
} from './routes/serialize-form-data.svelte'
import {
  Route as StatusRouteImport,
  default as StatusRouteComponent,
} from './routes/status.svelte'
import {
  Route as SubmitPostFormdataRouteImport,
  default as SubmitPostFormdataRouteComponent,
} from './routes/submit-post-formdata.svelte'
import {
  Route as CookiesIndexRouteImport,
  default as CookiesIndexRouteComponent,
} from './routes/cookies/index.svelte'
import {
  Route as CookiesSetRouteImport,
  default as CookiesSetRouteComponent,
} from './routes/cookies/set.svelte'
import {
  Route as FactoryIndexRouteImport,
  default as FactoryIndexRouteComponent,
} from './routes/factory/index.svelte'
import {
  Route as FormdataRedirectIndexRouteImport,
  default as FormdataRedirectIndexRouteComponent,
} from './routes/formdata-redirect/index.svelte'
import {
  Route as FunctionMetadataIndexRouteImport,
  default as FunctionMetadataIndexRouteComponent,
} from './routes/function-metadata/index.svelte'
import {
  Route as FunctionMethodIndexRouteImport,
  default as FunctionMethodIndexRouteComponent,
} from './routes/function-method/index.svelte'
import {
  Route as MiddlewareIndexRouteImport,
  default as MiddlewareIndexRouteComponent,
} from './routes/middleware/index.svelte'
import {
  Route as MiddlewareClientMiddlewareRouterRouteImport,
  default as MiddlewareClientMiddlewareRouterRouteComponent,
} from './routes/middleware/client-middleware-router.svelte'
import {
  Route as MiddlewareRequestMiddlewareRouteImport,
  default as MiddlewareRequestMiddlewareRouteComponent,
} from './routes/middleware/request-middleware.svelte'
import {
  Route as MiddlewareSendServerFnRouteImport,
  default as MiddlewareSendServerFnRouteComponent,
} from './routes/middleware/send-serverFn.svelte'
import {
  Route as PrimitivesIndexRouteImport,
  default as PrimitivesIndexRouteComponent,
} from './routes/primitives/index.svelte'
import {
  Route as RedirectTestSsrIndexRouteImport,
  default as RedirectTestSsrIndexRouteComponent,
} from './routes/redirect-test-ssr/index.svelte'
import {
  Route as RedirectTestSsrTargetRouteImport,
  default as RedirectTestSsrTargetRouteComponent,
} from './routes/redirect-test-ssr/target.svelte'
import {
  Route as RedirectTestIndexRouteImport,
  default as RedirectTestIndexRouteComponent,
} from './routes/redirect-test/index.svelte'
import {
  Route as RedirectTestTargetRouteImport,
  default as RedirectTestTargetRouteComponent,
} from './routes/redirect-test/target.svelte'
import {
  Route as FormdataRedirectTargetNameRouteImport,
  default as FormdataRedirectTargetNameRouteComponent,
} from './routes/formdata-redirect/target.$name.svelte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: IndexRouteComponent,
})
const AbortSignalRoute = AbortSignalRouteImport.update({
  id: '/abort-signal',
  path: '/abort-signal',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: AbortSignalRouteComponent,
})
const ConsistentRoute = ConsistentRouteImport.update({
  id: '/consistent',
  path: '/consistent',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: ConsistentRouteComponent,
})
const DeadCodePreserveRoute = DeadCodePreserveRouteImport.update({
  id: '/dead-code-preserve',
  path: '/dead-code-preserve',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: DeadCodePreserveRouteComponent,
})
const EnvOnlyRoute = EnvOnlyRouteImport.update({
  id: '/env-only',
  path: '/env-only',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: EnvOnlyRouteComponent,
})
const HeadersRoute = HeadersRouteImport.update({
  id: '/headers',
  path: '/headers',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: HeadersRouteComponent,
})
const IsomorphicFnsRoute = IsomorphicFnsRouteImport.update({
  id: '/isomorphic-fns',
  path: '/isomorphic-fns',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: IsomorphicFnsRouteComponent,
})
const MultipartRoute = MultipartRouteImport.update({
  id: '/multipart',
  path: '/multipart',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: MultipartRouteComponent,
})
const RawResponseRoute = RawResponseRouteImport.update({
  id: '/raw-response',
  path: '/raw-response',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: RawResponseRouteComponent,
})
const ReturnNullRoute = ReturnNullRouteImport.update({
  id: '/return-null',
  path: '/return-null',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: ReturnNullRouteComponent,
})
const SerializeFormDataRoute = SerializeFormDataRouteImport.update({
  id: '/serialize-form-data',
  path: '/serialize-form-data',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: SerializeFormDataRouteComponent,
})
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: StatusRouteComponent,
})
const SubmitPostFormdataRoute = SubmitPostFormdataRouteImport.update({
  id: '/submit-post-formdata',
  path: '/submit-post-formdata',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: SubmitPostFormdataRouteComponent,
})
const CookiesIndexRoute = CookiesIndexRouteImport.update({
  id: '/cookies/',
  path: '/cookies/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: CookiesIndexRouteComponent,
})
const CookiesSetRoute = CookiesSetRouteImport.update({
  id: '/cookies/set',
  path: '/cookies/set',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: CookiesSetRouteComponent,
})
const FactoryIndexRoute = FactoryIndexRouteImport.update({
  id: '/factory/',
  path: '/factory/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: FactoryIndexRouteComponent,
})
const FormdataRedirectIndexRoute = FormdataRedirectIndexRouteImport.update({
  id: '/formdata-redirect/',
  path: '/formdata-redirect/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: FormdataRedirectIndexRouteComponent,
})
const FunctionMetadataIndexRoute = FunctionMetadataIndexRouteImport.update({
  id: '/function-metadata/',
  path: '/function-metadata/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: FunctionMetadataIndexRouteComponent,
})
const FunctionMethodIndexRoute = FunctionMethodIndexRouteImport.update({
  id: '/function-method/',
  path: '/function-method/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: FunctionMethodIndexRouteComponent,
})
const MiddlewareIndexRoute = MiddlewareIndexRouteImport.update({
  id: '/middleware/',
  path: '/middleware/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: MiddlewareIndexRouteComponent,
})
const MiddlewareClientMiddlewareRouterRoute =
  MiddlewareClientMiddlewareRouterRouteImport.update({
    id: '/middleware/client-middleware-router',
    path: '/middleware/client-middleware-router',
    getParentRoute: () => rootRouteImport,
  } as any).update({
    component: MiddlewareClientMiddlewareRouterRouteComponent,
  })
const MiddlewareRequestMiddlewareRoute =
  MiddlewareRequestMiddlewareRouteImport.update({
    id: '/middleware/request-middleware',
    path: '/middleware/request-middleware',
    getParentRoute: () => rootRouteImport,
  } as any).update({
    component: MiddlewareRequestMiddlewareRouteComponent,
  })
const MiddlewareSendServerFnRoute = MiddlewareSendServerFnRouteImport.update({
  id: '/middleware/send-serverFn',
  path: '/middleware/send-serverFn',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: MiddlewareSendServerFnRouteComponent,
})
const PrimitivesIndexRoute = PrimitivesIndexRouteImport.update({
  id: '/primitives/',
  path: '/primitives/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: PrimitivesIndexRouteComponent,
})
const RedirectTestSsrIndexRoute = RedirectTestSsrIndexRouteImport.update({
  id: '/redirect-test-ssr/',
  path: '/redirect-test-ssr/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: RedirectTestSsrIndexRouteComponent,
})
const RedirectTestSsrTargetRoute = RedirectTestSsrTargetRouteImport.update({
  id: '/redirect-test-ssr/target',
  path: '/redirect-test-ssr/target',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: RedirectTestSsrTargetRouteComponent,
})
const RedirectTestIndexRoute = RedirectTestIndexRouteImport.update({
  id: '/redirect-test/',
  path: '/redirect-test/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: RedirectTestIndexRouteComponent,
})
const RedirectTestTargetRoute = RedirectTestTargetRouteImport.update({
  id: '/redirect-test/target',
  path: '/redirect-test/target',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: RedirectTestTargetRouteComponent,
})
const FormdataRedirectTargetNameRoute =
  FormdataRedirectTargetNameRouteImport.update({
    id: '/formdata-redirect/target/$name',
    path: '/formdata-redirect/target/$name',
    getParentRoute: () => rootRouteImport,
  } as any).update({
    component: FormdataRedirectTargetNameRouteComponent,
  })

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abort-signal': typeof AbortSignalRoute
  '/consistent': typeof ConsistentRoute
  '/dead-code-preserve': typeof DeadCodePreserveRoute
  '/env-only': typeof EnvOnlyRoute
  '/headers': typeof HeadersRoute
  '/isomorphic-fns': typeof IsomorphicFnsRoute
  '/multipart': typeof MultipartRoute
  '/raw-response': typeof RawResponseRoute
  '/return-null': typeof ReturnNullRoute
  '/serialize-form-data': typeof SerializeFormDataRoute
  '/status': typeof StatusRoute
  '/submit-post-formdata': typeof SubmitPostFormdataRoute
  '/cookies/set': typeof CookiesSetRoute
  '/middleware/client-middleware-router': typeof MiddlewareClientMiddlewareRouterRoute
  '/middleware/request-middleware': typeof MiddlewareRequestMiddlewareRoute
  '/middleware/send-serverFn': typeof MiddlewareSendServerFnRoute
  '/redirect-test-ssr/target': typeof RedirectTestSsrTargetRoute
  '/redirect-test/target': typeof RedirectTestTargetRoute
  '/cookies/': typeof CookiesIndexRoute
  '/factory/': typeof FactoryIndexRoute
  '/formdata-redirect/': typeof FormdataRedirectIndexRoute
  '/function-metadata/': typeof FunctionMetadataIndexRoute
  '/function-method/': typeof FunctionMethodIndexRoute
  '/middleware/': typeof MiddlewareIndexRoute
  '/primitives/': typeof PrimitivesIndexRoute
  '/redirect-test-ssr/': typeof RedirectTestSsrIndexRoute
  '/redirect-test/': typeof RedirectTestIndexRoute
  '/formdata-redirect/target/$name': typeof FormdataRedirectTargetNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abort-signal': typeof AbortSignalRoute
  '/consistent': typeof ConsistentRoute
  '/dead-code-preserve': typeof DeadCodePreserveRoute
  '/env-only': typeof EnvOnlyRoute
  '/headers': typeof HeadersRoute
  '/isomorphic-fns': typeof IsomorphicFnsRoute
  '/multipart': typeof MultipartRoute
  '/raw-response': typeof RawResponseRoute
  '/return-null': typeof ReturnNullRoute
  '/serialize-form-data': typeof SerializeFormDataRoute
  '/status': typeof StatusRoute
  '/submit-post-formdata': typeof SubmitPostFormdataRoute
  '/cookies/set': typeof CookiesSetRoute
  '/middleware/client-middleware-router': typeof MiddlewareClientMiddlewareRouterRoute
  '/middleware/request-middleware': typeof MiddlewareRequestMiddlewareRoute
  '/middleware/send-serverFn': typeof MiddlewareSendServerFnRoute
  '/redirect-test-ssr/target': typeof RedirectTestSsrTargetRoute
  '/redirect-test/target': typeof RedirectTestTargetRoute
  '/cookies': typeof CookiesIndexRoute
  '/factory': typeof FactoryIndexRoute
  '/formdata-redirect': typeof FormdataRedirectIndexRoute
  '/function-metadata': typeof FunctionMetadataIndexRoute
  '/function-method': typeof FunctionMethodIndexRoute
  '/middleware': typeof MiddlewareIndexRoute
  '/primitives': typeof PrimitivesIndexRoute
  '/redirect-test-ssr': typeof RedirectTestSsrIndexRoute
  '/redirect-test': typeof RedirectTestIndexRoute
  '/formdata-redirect/target/$name': typeof FormdataRedirectTargetNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abort-signal': typeof AbortSignalRoute
  '/consistent': typeof ConsistentRoute
  '/dead-code-preserve': typeof DeadCodePreserveRoute
  '/env-only': typeof EnvOnlyRoute
  '/headers': typeof HeadersRoute
  '/isomorphic-fns': typeof IsomorphicFnsRoute
  '/multipart': typeof MultipartRoute
  '/raw-response': typeof RawResponseRoute
  '/return-null': typeof ReturnNullRoute
  '/serialize-form-data': typeof SerializeFormDataRoute
  '/status': typeof StatusRoute
  '/submit-post-formdata': typeof SubmitPostFormdataRoute
  '/cookies/set': typeof CookiesSetRoute
  '/middleware/client-middleware-router': typeof MiddlewareClientMiddlewareRouterRoute
  '/middleware/request-middleware': typeof MiddlewareRequestMiddlewareRoute
  '/middleware/send-serverFn': typeof MiddlewareSendServerFnRoute
  '/redirect-test-ssr/target': typeof RedirectTestSsrTargetRoute
  '/redirect-test/target': typeof RedirectTestTargetRoute
  '/cookies/': typeof CookiesIndexRoute
  '/factory/': typeof FactoryIndexRoute
  '/formdata-redirect/': typeof FormdataRedirectIndexRoute
  '/function-metadata/': typeof FunctionMetadataIndexRoute
  '/function-method/': typeof FunctionMethodIndexRoute
  '/middleware/': typeof MiddlewareIndexRoute
  '/primitives/': typeof PrimitivesIndexRoute
  '/redirect-test-ssr/': typeof RedirectTestSsrIndexRoute
  '/redirect-test/': typeof RedirectTestIndexRoute
  '/formdata-redirect/target/$name': typeof FormdataRedirectTargetNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abort-signal'
    | '/consistent'
    | '/dead-code-preserve'
    | '/env-only'
    | '/headers'
    | '/isomorphic-fns'
    | '/multipart'
    | '/raw-response'
    | '/return-null'
    | '/serialize-form-data'
    | '/status'
    | '/submit-post-formdata'
    | '/cookies/set'
    | '/middleware/client-middleware-router'
    | '/middleware/request-middleware'
    | '/middleware/send-serverFn'
    | '/redirect-test-ssr/target'
    | '/redirect-test/target'
    | '/cookies/'
    | '/factory/'
    | '/formdata-redirect/'
    | '/function-metadata/'
    | '/function-method/'
    | '/middleware/'
    | '/primitives/'
    | '/redirect-test-ssr/'
    | '/redirect-test/'
    | '/formdata-redirect/target/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abort-signal'
    | '/consistent'
    | '/dead-code-preserve'
    | '/env-only'
    | '/headers'
    | '/isomorphic-fns'
    | '/multipart'
    | '/raw-response'
    | '/return-null'
    | '/serialize-form-data'
    | '/status'
    | '/submit-post-formdata'
    | '/cookies/set'
    | '/middleware/client-middleware-router'
    | '/middleware/request-middleware'
    | '/middleware/send-serverFn'
    | '/redirect-test-ssr/target'
    | '/redirect-test/target'
    | '/cookies'
    | '/factory'
    | '/formdata-redirect'
    | '/function-metadata'
    | '/function-method'
    | '/middleware'
    | '/primitives'
    | '/redirect-test-ssr'
    | '/redirect-test'
    | '/formdata-redirect/target/$name'
  id:
    | '__root__'
    | '/'
    | '/abort-signal'
    | '/consistent'
    | '/dead-code-preserve'
    | '/env-only'
    | '/headers'
    | '/isomorphic-fns'
    | '/multipart'
    | '/raw-response'
    | '/return-null'
    | '/serialize-form-data'
    | '/status'
    | '/submit-post-formdata'
    | '/cookies/set'
    | '/middleware/client-middleware-router'
    | '/middleware/request-middleware'
    | '/middleware/send-serverFn'
    | '/redirect-test-ssr/target'
    | '/redirect-test/target'
    | '/cookies/'
    | '/factory/'
    | '/formdata-redirect/'
    | '/function-metadata/'
    | '/function-method/'
    | '/middleware/'
    | '/primitives/'
    | '/redirect-test-ssr/'
    | '/redirect-test/'
    | '/formdata-redirect/target/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbortSignalRoute: typeof AbortSignalRoute
  ConsistentRoute: typeof ConsistentRoute
  DeadCodePreserveRoute: typeof DeadCodePreserveRoute
  EnvOnlyRoute: typeof EnvOnlyRoute
  HeadersRoute: typeof HeadersRoute
  IsomorphicFnsRoute: typeof IsomorphicFnsRoute
  MultipartRoute: typeof MultipartRoute
  RawResponseRoute: typeof RawResponseRoute
  ReturnNullRoute: typeof ReturnNullRoute
  SerializeFormDataRoute: typeof SerializeFormDataRoute
  StatusRoute: typeof StatusRoute
  SubmitPostFormdataRoute: typeof SubmitPostFormdataRoute
  CookiesSetRoute: typeof CookiesSetRoute
  MiddlewareClientMiddlewareRouterRoute: typeof MiddlewareClientMiddlewareRouterRoute
  MiddlewareRequestMiddlewareRoute: typeof MiddlewareRequestMiddlewareRoute
  MiddlewareSendServerFnRoute: typeof MiddlewareSendServerFnRoute
  RedirectTestSsrTargetRoute: typeof RedirectTestSsrTargetRoute
  RedirectTestTargetRoute: typeof RedirectTestTargetRoute
  CookiesIndexRoute: typeof CookiesIndexRoute
  FactoryIndexRoute: typeof FactoryIndexRoute
  FormdataRedirectIndexRoute: typeof FormdataRedirectIndexRoute
  FunctionMetadataIndexRoute: typeof FunctionMetadataIndexRoute
  FunctionMethodIndexRoute: typeof FunctionMethodIndexRoute
  MiddlewareIndexRoute: typeof MiddlewareIndexRoute
  PrimitivesIndexRoute: typeof PrimitivesIndexRoute
  RedirectTestSsrIndexRoute: typeof RedirectTestSsrIndexRoute
  RedirectTestIndexRoute: typeof RedirectTestIndexRoute
  FormdataRedirectTargetNameRoute: typeof FormdataRedirectTargetNameRoute
}

declare module '@tanstack/svelte-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abort-signal': {
      id: '/abort-signal'
      path: '/abort-signal'
      fullPath: '/abort-signal'
      preLoaderRoute: typeof AbortSignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consistent': {
      id: '/consistent'
      path: '/consistent'
      fullPath: '/consistent'
      preLoaderRoute: typeof ConsistentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dead-code-preserve': {
      id: '/dead-code-preserve'
      path: '/dead-code-preserve'
      fullPath: '/dead-code-preserve'
      preLoaderRoute: typeof DeadCodePreserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/env-only': {
      id: '/env-only'
      path: '/env-only'
      fullPath: '/env-only'
      preLoaderRoute: typeof EnvOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headers': {
      id: '/headers'
      path: '/headers'
      fullPath: '/headers'
      preLoaderRoute: typeof HeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isomorphic-fns': {
      id: '/isomorphic-fns'
      path: '/isomorphic-fns'
      fullPath: '/isomorphic-fns'
      preLoaderRoute: typeof IsomorphicFnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multipart': {
      id: '/multipart'
      path: '/multipart'
      fullPath: '/multipart'
      preLoaderRoute: typeof MultipartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw-response': {
      id: '/raw-response'
      path: '/raw-response'
      fullPath: '/raw-response'
      preLoaderRoute: typeof RawResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-null': {
      id: '/return-null'
      path: '/return-null'
      fullPath: '/return-null'
      preLoaderRoute: typeof ReturnNullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serialize-form-data': {
      id: '/serialize-form-data'
      path: '/serialize-form-data'
      fullPath: '/serialize-form-data'
      preLoaderRoute: typeof SerializeFormDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-post-formdata': {
      id: '/submit-post-formdata'
      path: '/submit-post-formdata'
      fullPath: '/submit-post-formdata'
      preLoaderRoute: typeof SubmitPostFormdataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies/': {
      id: '/cookies/'
      path: '/cookies'
      fullPath: '/cookies/'
      preLoaderRoute: typeof CookiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies/set': {
      id: '/cookies/set'
      path: '/cookies/set'
      fullPath: '/cookies/set'
      preLoaderRoute: typeof CookiesSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory/': {
      id: '/factory/'
      path: '/factory'
      fullPath: '/factory/'
      preLoaderRoute: typeof FactoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formdata-redirect/': {
      id: '/formdata-redirect/'
      path: '/formdata-redirect'
      fullPath: '/formdata-redirect/'
      preLoaderRoute: typeof FormdataRedirectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/function-metadata/': {
      id: '/function-metadata/'
      path: '/function-metadata'
      fullPath: '/function-metadata/'
      preLoaderRoute: typeof FunctionMetadataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/function-method/': {
      id: '/function-method/'
      path: '/function-method'
      fullPath: '/function-method/'
      preLoaderRoute: typeof FunctionMethodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/middleware/': {
      id: '/middleware/'
      path: '/middleware'
      fullPath: '/middleware/'
      preLoaderRoute: typeof MiddlewareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/middleware/client-middleware-router': {
      id: '/middleware/client-middleware-router'
      path: '/middleware/client-middleware-router'
      fullPath: '/middleware/client-middleware-router'
      preLoaderRoute: typeof MiddlewareClientMiddlewareRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/middleware/request-middleware': {
      id: '/middleware/request-middleware'
      path: '/middleware/request-middleware'
      fullPath: '/middleware/request-middleware'
      preLoaderRoute: typeof MiddlewareRequestMiddlewareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/middleware/send-serverFn': {
      id: '/middleware/send-serverFn'
      path: '/middleware/send-serverFn'
      fullPath: '/middleware/send-serverFn'
      preLoaderRoute: typeof MiddlewareSendServerFnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primitives/': {
      id: '/primitives/'
      path: '/primitives'
      fullPath: '/primitives/'
      preLoaderRoute: typeof PrimitivesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect-test-ssr/': {
      id: '/redirect-test-ssr/'
      path: '/redirect-test-ssr'
      fullPath: '/redirect-test-ssr/'
      preLoaderRoute: typeof RedirectTestSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect-test-ssr/target': {
      id: '/redirect-test-ssr/target'
      path: '/redirect-test-ssr/target'
      fullPath: '/redirect-test-ssr/target'
      preLoaderRoute: typeof RedirectTestSsrTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect-test/': {
      id: '/redirect-test/'
      path: '/redirect-test'
      fullPath: '/redirect-test/'
      preLoaderRoute: typeof RedirectTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect-test/target': {
      id: '/redirect-test/target'
      path: '/redirect-test/target'
      fullPath: '/redirect-test/target'
      preLoaderRoute: typeof RedirectTestTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formdata-redirect/target/$name': {
      id: '/formdata-redirect/target/$name'
      path: '/formdata-redirect/target/$name'
      fullPath: '/formdata-redirect/target/$name'
      preLoaderRoute: typeof FormdataRedirectTargetNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbortSignalRoute: AbortSignalRoute,
  ConsistentRoute: ConsistentRoute,
  DeadCodePreserveRoute: DeadCodePreserveRoute,
  EnvOnlyRoute: EnvOnlyRoute,
  HeadersRoute: HeadersRoute,
  IsomorphicFnsRoute: IsomorphicFnsRoute,
  MultipartRoute: MultipartRoute,
  RawResponseRoute: RawResponseRoute,
  ReturnNullRoute: ReturnNullRoute,
  SerializeFormDataRoute: SerializeFormDataRoute,
  StatusRoute: StatusRoute,
  SubmitPostFormdataRoute: SubmitPostFormdataRoute,
  CookiesSetRoute: CookiesSetRoute,
  MiddlewareClientMiddlewareRouterRoute: MiddlewareClientMiddlewareRouterRoute,
  MiddlewareRequestMiddlewareRoute: MiddlewareRequestMiddlewareRoute,
  MiddlewareSendServerFnRoute: MiddlewareSendServerFnRoute,
  RedirectTestSsrTargetRoute: RedirectTestSsrTargetRoute,
  RedirectTestTargetRoute: RedirectTestTargetRoute,
  CookiesIndexRoute: CookiesIndexRoute,
  FactoryIndexRoute: FactoryIndexRoute,
  FormdataRedirectIndexRoute: FormdataRedirectIndexRoute,
  FunctionMetadataIndexRoute: FunctionMetadataIndexRoute,
  FunctionMethodIndexRoute: FunctionMethodIndexRoute,
  MiddlewareIndexRoute: MiddlewareIndexRoute,
  PrimitivesIndexRoute: PrimitivesIndexRoute,
  RedirectTestSsrIndexRoute: RedirectTestSsrIndexRoute,
  RedirectTestIndexRoute: RedirectTestIndexRoute,
  FormdataRedirectTargetNameRoute: FormdataRedirectTargetNameRoute,
}
export const routeTree = rootRouteImport
  .update({
    component: rootRouteComponent,
  })
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/svelte-start'
declare module '@tanstack/svelte-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
