/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { lazyRouteComponent } from '@tanstack/svelte-router'

import {
  Route as rootRouteImport,
  default as rootRouteComponent,
} from './routes/__root.svelte'
import {
  Route as IndexRouteImport,
  default as IndexRouteComponent,
} from './routes/index.svelte'
import {
  Route as UseQueryRouteImport,
  default as UseQueryRouteComponent,
} from './routes/useQuery.svelte'
import {
  Route as LoaderFetchQueryTypeRouteImport,
  default as LoaderFetchQueryTypeRouteComponent,
} from './routes/loader-fetchQuery/$type.svelte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: IndexRouteComponent,
})
const UseQueryRoute = UseQueryRouteImport.update({
  id: '/useQuery',
  path: '/useQuery',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: UseQueryRouteComponent,
})
const LoaderFetchQueryTypeRoute = LoaderFetchQueryTypeRouteImport.update({
  id: '/loader-fetchQuery/$type',
  path: '/loader-fetchQuery/$type',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: LoaderFetchQueryTypeRouteComponent,
})

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/useQuery': typeof UseQueryRoute
  '/loader-fetchQuery/$type': typeof LoaderFetchQueryTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/useQuery': typeof UseQueryRoute
  '/loader-fetchQuery/$type': typeof LoaderFetchQueryTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/useQuery': typeof UseQueryRoute
  '/loader-fetchQuery/$type': typeof LoaderFetchQueryTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/useQuery' | '/loader-fetchQuery/$type'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/useQuery' | '/loader-fetchQuery/$type'
  id: '__root__' | '/' | '/useQuery' | '/loader-fetchQuery/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UseQueryRoute: typeof UseQueryRoute
  LoaderFetchQueryTypeRoute: typeof LoaderFetchQueryTypeRoute
}

declare module '@tanstack/svelte-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useQuery': {
      id: '/useQuery'
      path: '/useQuery'
      fullPath: '/useQuery'
      preLoaderRoute: typeof UseQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loader-fetchQuery/$type': {
      id: '/loader-fetchQuery/$type'
      path: '/loader-fetchQuery/$type'
      fullPath: '/loader-fetchQuery/$type'
      preLoaderRoute: typeof LoaderFetchQueryTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UseQueryRoute: UseQueryRoute,
  LoaderFetchQueryTypeRoute: LoaderFetchQueryTypeRoute,
}
export const routeTree = rootRouteImport
  .update({
    component: rootRouteComponent,
  })
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/svelte-start'
declare module '@tanstack/svelte-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
