/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { lazyRouteComponent } from '@tanstack/svelte-router'

import {
  Route as rootRouteImport,
  default as rootRouteComponent,
} from './routes/__root.svelte'
import {
  Route as IndexRouteImport,
  default as IndexRouteComponent,
} from './routes/index.svelte'
import {
  Route as ConcurrentRouteImport,
  default as ConcurrentRouteComponent,
} from './routes/concurrent.svelte'
import {
  Route as DeferredRouteImport,
  default as DeferredRouteComponent,
} from './routes/deferred.svelte'
import {
  Route as DeferredRejectionRouteImport,
  default as DeferredRejectionRouteComponent,
} from './routes/deferred-rejection.svelte'
import {
  Route as FastSerialRouteImport,
  default as FastSerialRouteComponent,
} from './routes/fast-serial.svelte'
import {
  Route as ManyPromisesRouteImport,
  default as ManyPromisesRouteComponent,
} from './routes/many-promises.svelte'
import {
  Route as NestedDeferredRouteImport,
  default as NestedDeferredRouteComponent,
} from './routes/nested-deferred.svelte'
import {
  Route as QueryHeavyRouteImport,
  default as QueryHeavyRouteComponent,
} from './routes/query-heavy.svelte'
import {
  Route as SlowRenderRouteImport,
  default as SlowRenderRouteComponent,
} from './routes/slow-render.svelte'
import {
  Route as StreamRouteImport,
  default as StreamRouteComponent,
} from './routes/stream.svelte'
import {
  Route as SyncOnlyRouteImport,
  default as SyncOnlyRouteComponent,
} from './routes/sync-only.svelte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: IndexRouteComponent,
})
const ConcurrentRoute = ConcurrentRouteImport.update({
  id: '/concurrent',
  path: '/concurrent',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: ConcurrentRouteComponent,
})
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: DeferredRouteComponent,
})
const DeferredRejectionRoute = DeferredRejectionRouteImport.update({
  id: '/deferred-rejection',
  path: '/deferred-rejection',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: DeferredRejectionRouteComponent,
})
const FastSerialRoute = FastSerialRouteImport.update({
  id: '/fast-serial',
  path: '/fast-serial',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: FastSerialRouteComponent,
})
const ManyPromisesRoute = ManyPromisesRouteImport.update({
  id: '/many-promises',
  path: '/many-promises',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: ManyPromisesRouteComponent,
})
const NestedDeferredRoute = NestedDeferredRouteImport.update({
  id: '/nested-deferred',
  path: '/nested-deferred',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: NestedDeferredRouteComponent,
})
const QueryHeavyRoute = QueryHeavyRouteImport.update({
  id: '/query-heavy',
  path: '/query-heavy',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: QueryHeavyRouteComponent,
})
const SlowRenderRoute = SlowRenderRouteImport.update({
  id: '/slow-render',
  path: '/slow-render',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: SlowRenderRouteComponent,
})
const StreamRoute = StreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: StreamRouteComponent,
})
const SyncOnlyRoute = SyncOnlyRouteImport.update({
  id: '/sync-only',
  path: '/sync-only',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: SyncOnlyRouteComponent,
})

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concurrent': typeof ConcurrentRoute
  '/deferred': typeof DeferredRoute
  '/deferred-rejection': typeof DeferredRejectionRoute
  '/fast-serial': typeof FastSerialRoute
  '/many-promises': typeof ManyPromisesRoute
  '/nested-deferred': typeof NestedDeferredRoute
  '/query-heavy': typeof QueryHeavyRoute
  '/slow-render': typeof SlowRenderRoute
  '/stream': typeof StreamRoute
  '/sync-only': typeof SyncOnlyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concurrent': typeof ConcurrentRoute
  '/deferred': typeof DeferredRoute
  '/deferred-rejection': typeof DeferredRejectionRoute
  '/fast-serial': typeof FastSerialRoute
  '/many-promises': typeof ManyPromisesRoute
  '/nested-deferred': typeof NestedDeferredRoute
  '/query-heavy': typeof QueryHeavyRoute
  '/slow-render': typeof SlowRenderRoute
  '/stream': typeof StreamRoute
  '/sync-only': typeof SyncOnlyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concurrent': typeof ConcurrentRoute
  '/deferred': typeof DeferredRoute
  '/deferred-rejection': typeof DeferredRejectionRoute
  '/fast-serial': typeof FastSerialRoute
  '/many-promises': typeof ManyPromisesRoute
  '/nested-deferred': typeof NestedDeferredRoute
  '/query-heavy': typeof QueryHeavyRoute
  '/slow-render': typeof SlowRenderRoute
  '/stream': typeof StreamRoute
  '/sync-only': typeof SyncOnlyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concurrent'
    | '/deferred'
    | '/deferred-rejection'
    | '/fast-serial'
    | '/many-promises'
    | '/nested-deferred'
    | '/query-heavy'
    | '/slow-render'
    | '/stream'
    | '/sync-only'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/concurrent'
    | '/deferred'
    | '/deferred-rejection'
    | '/fast-serial'
    | '/many-promises'
    | '/nested-deferred'
    | '/query-heavy'
    | '/slow-render'
    | '/stream'
    | '/sync-only'
  id:
    | '__root__'
    | '/'
    | '/concurrent'
    | '/deferred'
    | '/deferred-rejection'
    | '/fast-serial'
    | '/many-promises'
    | '/nested-deferred'
    | '/query-heavy'
    | '/slow-render'
    | '/stream'
    | '/sync-only'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConcurrentRoute: typeof ConcurrentRoute
  DeferredRoute: typeof DeferredRoute
  DeferredRejectionRoute: typeof DeferredRejectionRoute
  FastSerialRoute: typeof FastSerialRoute
  ManyPromisesRoute: typeof ManyPromisesRoute
  NestedDeferredRoute: typeof NestedDeferredRoute
  QueryHeavyRoute: typeof QueryHeavyRoute
  SlowRenderRoute: typeof SlowRenderRoute
  StreamRoute: typeof StreamRoute
  SyncOnlyRoute: typeof SyncOnlyRoute
}

declare module '@tanstack/svelte-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concurrent': {
      id: '/concurrent'
      path: '/concurrent'
      fullPath: '/concurrent'
      preLoaderRoute: typeof ConcurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred-rejection': {
      id: '/deferred-rejection'
      path: '/deferred-rejection'
      fullPath: '/deferred-rejection'
      preLoaderRoute: typeof DeferredRejectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fast-serial': {
      id: '/fast-serial'
      path: '/fast-serial'
      fullPath: '/fast-serial'
      preLoaderRoute: typeof FastSerialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/many-promises': {
      id: '/many-promises'
      path: '/many-promises'
      fullPath: '/many-promises'
      preLoaderRoute: typeof ManyPromisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nested-deferred': {
      id: '/nested-deferred'
      path: '/nested-deferred'
      fullPath: '/nested-deferred'
      preLoaderRoute: typeof NestedDeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-heavy': {
      id: '/query-heavy'
      path: '/query-heavy'
      fullPath: '/query-heavy'
      preLoaderRoute: typeof QueryHeavyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slow-render': {
      id: '/slow-render'
      path: '/slow-render'
      fullPath: '/slow-render'
      preLoaderRoute: typeof SlowRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream': {
      id: '/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync-only': {
      id: '/sync-only'
      path: '/sync-only'
      fullPath: '/sync-only'
      preLoaderRoute: typeof SyncOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConcurrentRoute: ConcurrentRoute,
  DeferredRoute: DeferredRoute,
  DeferredRejectionRoute: DeferredRejectionRoute,
  FastSerialRoute: FastSerialRoute,
  ManyPromisesRoute: ManyPromisesRoute,
  NestedDeferredRoute: NestedDeferredRoute,
  QueryHeavyRoute: QueryHeavyRoute,
  SlowRenderRoute: SlowRenderRoute,
  StreamRoute: StreamRoute,
  SyncOnlyRoute: SyncOnlyRoute,
}
export const routeTree = rootRouteImport
  .update({
    component: rootRouteComponent,
  })
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/svelte-start'
declare module '@tanstack/svelte-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
