/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute, lazyRouteComponent } from '@tanstack/svelte-router'

import {
  Route as rootRouteImport,
  default as rootRouteComponent,
} from './routes/__root.svelte'

const IndexRouteImport = createFileRoute('/')()
const ARouteImport = createFileRoute('/a')()
const BRouteImport = createFileRoute('/b')()
const LazyCssLazyRouteImport = createFileRoute('/lazy-css-lazy')()
const LazyCssStaticRouteImport = createFileRoute('/lazy-css-static')()
const R1RouteImport = createFileRoute('/r1')()
const R2RouteImport = createFileRoute('/r2')()
const R3RouteImport = createFileRoute('/r3')()
const R4RouteImport = createFileRoute('/r4')()
const R5RouteImport = createFileRoute('/r5')()
const R6RouteImport = createFileRoute('/r6')()
const SharedARouteImport = createFileRoute('/shared-a')()
const SharedBRouteImport = createFileRoute('/shared-b')()
const SharedCRouteImport = createFileRoute('/shared-c')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/index.svelte'),
    'default',
  ),
})
const ARoute = ARouteImport.update({
  id: '/a',
  path: '/a',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(() => import('./routes/a.svelte'), 'default'),
})
const BRoute = BRouteImport.update({
  id: '/b',
  path: '/b',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(() => import('./routes/b.svelte'), 'default'),
})
const LazyCssLazyRoute = LazyCssLazyRouteImport.update({
  id: '/lazy-css-lazy',
  path: '/lazy-css-lazy',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/lazy-css-lazy.svelte'),
    'default',
  ),
})
const LazyCssStaticRoute = LazyCssStaticRouteImport.update({
  id: '/lazy-css-static',
  path: '/lazy-css-static',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/lazy-css-static.svelte'),
    'default',
  ),
})
const R1Route = R1RouteImport.update({
  id: '/r1',
  path: '/r1',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(() => import('./routes/r1.svelte'), 'default'),
})
const R2Route = R2RouteImport.update({
  id: '/r2',
  path: '/r2',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(() => import('./routes/r2.svelte'), 'default'),
})
const R3Route = R3RouteImport.update({
  id: '/r3',
  path: '/r3',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(() => import('./routes/r3.svelte'), 'default'),
})
const R4Route = R4RouteImport.update({
  id: '/r4',
  path: '/r4',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(() => import('./routes/r4.svelte'), 'default'),
})
const R5Route = R5RouteImport.update({
  id: '/r5',
  path: '/r5',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(() => import('./routes/r5.svelte'), 'default'),
})
const R6Route = R6RouteImport.update({
  id: '/r6',
  path: '/r6',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(() => import('./routes/r6.svelte'), 'default'),
})
const SharedARoute = SharedARouteImport.update({
  id: '/shared-a',
  path: '/shared-a',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/shared-a.svelte'),
    'default',
  ),
})
const SharedBRoute = SharedBRouteImport.update({
  id: '/shared-b',
  path: '/shared-b',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/shared-b.svelte'),
    'default',
  ),
})
const SharedCRoute = SharedCRouteImport.update({
  id: '/shared-c',
  path: '/shared-c',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/shared-c.svelte'),
    'default',
  ),
})

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a': typeof ARoute
  '/b': typeof BRoute
  '/lazy-css-lazy': typeof LazyCssLazyRoute
  '/lazy-css-static': typeof LazyCssStaticRoute
  '/r1': typeof R1Route
  '/r2': typeof R2Route
  '/r3': typeof R3Route
  '/r4': typeof R4Route
  '/r5': typeof R5Route
  '/r6': typeof R6Route
  '/shared-a': typeof SharedARoute
  '/shared-b': typeof SharedBRoute
  '/shared-c': typeof SharedCRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a': typeof ARoute
  '/b': typeof BRoute
  '/lazy-css-lazy': typeof LazyCssLazyRoute
  '/lazy-css-static': typeof LazyCssStaticRoute
  '/r1': typeof R1Route
  '/r2': typeof R2Route
  '/r3': typeof R3Route
  '/r4': typeof R4Route
  '/r5': typeof R5Route
  '/r6': typeof R6Route
  '/shared-a': typeof SharedARoute
  '/shared-b': typeof SharedBRoute
  '/shared-c': typeof SharedCRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a': typeof ARoute
  '/b': typeof BRoute
  '/lazy-css-lazy': typeof LazyCssLazyRoute
  '/lazy-css-static': typeof LazyCssStaticRoute
  '/r1': typeof R1Route
  '/r2': typeof R2Route
  '/r3': typeof R3Route
  '/r4': typeof R4Route
  '/r5': typeof R5Route
  '/r6': typeof R6Route
  '/shared-a': typeof SharedARoute
  '/shared-b': typeof SharedBRoute
  '/shared-c': typeof SharedCRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a'
    | '/b'
    | '/lazy-css-lazy'
    | '/lazy-css-static'
    | '/r1'
    | '/r2'
    | '/r3'
    | '/r4'
    | '/r5'
    | '/r6'
    | '/shared-a'
    | '/shared-b'
    | '/shared-c'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a'
    | '/b'
    | '/lazy-css-lazy'
    | '/lazy-css-static'
    | '/r1'
    | '/r2'
    | '/r3'
    | '/r4'
    | '/r5'
    | '/r6'
    | '/shared-a'
    | '/shared-b'
    | '/shared-c'
  id:
    | '__root__'
    | '/'
    | '/a'
    | '/b'
    | '/lazy-css-lazy'
    | '/lazy-css-static'
    | '/r1'
    | '/r2'
    | '/r3'
    | '/r4'
    | '/r5'
    | '/r6'
    | '/shared-a'
    | '/shared-b'
    | '/shared-c'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ARoute: typeof ARoute
  BRoute: typeof BRoute
  LazyCssLazyRoute: typeof LazyCssLazyRoute
  LazyCssStaticRoute: typeof LazyCssStaticRoute
  R1Route: typeof R1Route
  R2Route: typeof R2Route
  R3Route: typeof R3Route
  R4Route: typeof R4Route
  R5Route: typeof R5Route
  R6Route: typeof R6Route
  SharedARoute: typeof SharedARoute
  SharedBRoute: typeof SharedBRoute
  SharedCRoute: typeof SharedCRoute
}

declare module '@tanstack/svelte-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a': {
      id: '/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof ARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b': {
      id: '/b'
      path: '/b'
      fullPath: '/b'
      preLoaderRoute: typeof BRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lazy-css-lazy': {
      id: '/lazy-css-lazy'
      path: '/lazy-css-lazy'
      fullPath: '/lazy-css-lazy'
      preLoaderRoute: typeof LazyCssLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lazy-css-static': {
      id: '/lazy-css-static'
      path: '/lazy-css-static'
      fullPath: '/lazy-css-static'
      preLoaderRoute: typeof LazyCssStaticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r1': {
      id: '/r1'
      path: '/r1'
      fullPath: '/r1'
      preLoaderRoute: typeof R1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r2': {
      id: '/r2'
      path: '/r2'
      fullPath: '/r2'
      preLoaderRoute: typeof R2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r3': {
      id: '/r3'
      path: '/r3'
      fullPath: '/r3'
      preLoaderRoute: typeof R3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r4': {
      id: '/r4'
      path: '/r4'
      fullPath: '/r4'
      preLoaderRoute: typeof R4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r5': {
      id: '/r5'
      path: '/r5'
      fullPath: '/r5'
      preLoaderRoute: typeof R5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r6': {
      id: '/r6'
      path: '/r6'
      fullPath: '/r6'
      preLoaderRoute: typeof R6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-a': {
      id: '/shared-a'
      path: '/shared-a'
      fullPath: '/shared-a'
      preLoaderRoute: typeof SharedARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-b': {
      id: '/shared-b'
      path: '/shared-b'
      fullPath: '/shared-b'
      preLoaderRoute: typeof SharedBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-c': {
      id: '/shared-c'
      path: '/shared-c'
      fullPath: '/shared-c'
      preLoaderRoute: typeof SharedCRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ARoute: ARoute,
  BRoute: BRoute,
  LazyCssLazyRoute: LazyCssLazyRoute,
  LazyCssStaticRoute: LazyCssStaticRoute,
  R1Route: R1Route,
  R2Route: R2Route,
  R3Route: R3Route,
  R4Route: R4Route,
  R5Route: R5Route,
  R6Route: R6Route,
  SharedARoute: SharedARoute,
  SharedBRoute: SharedBRoute,
  SharedCRoute: SharedCRoute,
}
export const routeTree = rootRouteImport
  .update({
    component: rootRouteComponent,
  })
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/svelte-start'
declare module '@tanstack/svelte-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
